apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-github
  labels:
    app: pod-github
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-github
  template:
    metadata:
      labels:
        app: pod-github
    spec:
      containers:
      - name: pod-github
        image: worthy98/c-n-c:1
        ports:
        - containerPort: 8000